import type { CashEntry, Shipment } from "./types";

const day = 86400000;
const iso = (offset: number) => new Date(Date.now() + offset * day).toISOString();
const time = (offset: number, h: number, m: number) => {
  const d = new Date(Date.now() + offset * day);
  d.setHours(h, m, 0, 0);
  return d.toISOString();
};

/** Seed data is built lazily (never at module scope) to stay worker-safe. */
export function makeSeedShipments(): Shipment[] {
  return [
    {
      id: "SEA-8842",
      customer_name: "Al Barsha Trading LLC",
      customer_phone: "+971 50 118 4420",
      customer_language: "en",
      shipper: "Al Barsha Trading LLC",
      consignee: "Nile Delta Imports",
      cargo_type: "Aluminium profiles",
      weight: 18400,
      origin: "Jebel Ali, Dubai",
      destination: "Port Said, Egypt",
      mode: "sea",
      booking_date: iso(-6),
      status: "in_transit",
      cod_amount: 18400,
      missing_docs: ["bill_of_lading"],
      ai_summary: {
        en: "A 18.4-tonne sea shipment of aluminium profiles left Jebel Ali for Port Said and is currently in transit. The bill of lading is still outstanding, which may hold up release at destination. COD of AED 18,400 is due on arrival.",
        ar: "شحنة بحرية بوزن ١٨.٤ طن من مقاطع الألمنيوم غادرت جبل علي متجهة إلى بورسعيد وهي حاليًا قيد النقل. بوليصة الشحن لم تُستلم بعد، مما قد يؤخر الإفراج في الوجهة. مبلغ ١٨٬٤٠٠ درهم مستحق عند الاستلام.",
      },
      whatsapp_log: [
        {
          id: "w1",
          direction: "out",
          text: "Hello Al Barsha Trading — your shipment SEA-8842 has departed Jebel Ali and is now In Transit to Port Said. Estimated arrival: 9 days.",
          timestamp: time(-6, 9, 12),
          buttons: ["Confirm", "Contact driver"],
        },
        {
          id: "w2",
          direction: "in",
          text: "Thanks. Please share the BL once issued.",
          timestamp: time(-6, 9, 31),
        },
      ],
      cost_breakdown: [
        { id: "c1", item: "Jebel Ali storage (4 days)", amount: 1150, category: "warehousing" },
        { id: "c2", item: "Export clearance", amount: 900, category: "broker" },
        { id: "c3", item: "Yard haulage", amount: 640, category: "trucking" },
        { id: "c4", item: "Forwarding fee", amount: 1800, category: "service_fee" },
      ],
      partner_coordination_log: [
        {
          id: "p1",
          party: "Gulf Line Origin Agent",
          role: "origin_agent",
          text: "Container stuffed and gated in. VGM submitted.",
          timestamp: time(-6, 8, 5),
        },
        {
          id: "p2",
          party: "Marsa Customs Brokers",
          role: "customs_broker",
          text: "Awaiting BL copy to file destination entry.",
          timestamp: time(-2, 11, 40),
        },
      ],
      created_at: iso(-6),
    },
    {
      id: "AIR-9012",
      customer_name: "شركة واحة الخليج للتجارة",
      customer_phone: "+971 55 902 3311",
      customer_language: "ar",
      shipper: "Gulf Oasis Trading Co.",
      consignee: "Narita Components KK",
      cargo_type: "Electronic components",
      weight: 420,
      origin: "DXB Cargo Terminal, Dubai",
      destination: "Narita, Japan",
      mode: "air",
      booking_date: iso(-11),
      status: "delivered",
      cod_amount: 0,
      missing_docs: [],
      ai_summary: {
        en: "A 420 kg air freight consignment of electronic components flew DXB to Narita and has been delivered. All four required documents are on file and no COD applies.",
        ar: "شحنة جوية بوزن ٤٢٠ كجم من المكونات الإلكترونية سافرت من دبي إلى ناريتا وتم تسليمها. جميع المستندات الأربعة المطلوبة مكتملة ولا يوجد مبلغ مستحق عند الاستلام.",
      },
      whatsapp_log: [
        {
          id: "w1",
          direction: "out",
          text: "مرحبًا، شحنتكم AIR-9012 أقلعت من دبي وهي الآن قيد النقل إلى ناريتا.",
          timestamp: time(-11, 7, 45),
          buttons: ["تأكيد"],
        },
        {
          id: "w2",
          direction: "out",
          text: "تم تسليم شحنتكم AIR-9012 بنجاح. شكرًا لتعاملكم معنا.",
          timestamp: time(-8, 15, 20),
          buttons: ["تأكيد", "إعادة الجدولة"],
        },
      ],
      cost_breakdown: [
        { id: "c1", item: "Airline handling", amount: 2300, category: "warehousing" },
        { id: "c2", item: "Export documentation", amount: 550, category: "broker" },
        { id: "c3", item: "Airport delivery", amount: 480, category: "trucking" },
        { id: "c4", item: "Forwarding fee", amount: 1400, category: "service_fee" },
      ],
      partner_coordination_log: [
        {
          id: "p1",
          party: "Sakura Last-Mile",
          role: "last_mile",
          text: "POD uploaded, signed by consignee warehouse.",
          timestamp: time(-8, 15, 10),
        },
      ],
      created_at: iso(-11),
    },
    {
      id: "LND-2291",
      customer_name: "Oasis Construction Supplies",
      customer_phone: "+971 52 441 7788",
      customer_language: "en",
      shipper: "Oasis Construction Supplies",
      consignee: "Riyadh Build Depot",
      cargo_type: "Scaffolding sets",
      weight: 9600,
      origin: "Mussafah, Abu Dhabi",
      destination: "Riyadh, KSA",
      mode: "land",
      booking_date: iso(-3),
      status: "failed",
      cod_amount: 12800,
      missing_docs: ["certificate_of_origin", "packing_list"],
      ai_summary: {
        en: "A 9.6-tonne road shipment of scaffolding from Mussafah to Riyadh failed its first delivery attempt at the border checkpoint. Two documents are missing, and AED 12,800 COD remains uncollected.",
        ar: "شحنة برية بوزن ٩.٦ طن من السقالات من مصفح إلى الرياض فشلت في محاولة التسليم الأولى عند نقطة الحدود. هناك مستندان ناقصان، ولم يتم تحصيل ١٢٬٨٠٠ درهم عند الاستلام.",
      },
      whatsapp_log: [
        {
          id: "w1",
          direction: "out",
          text: "Delivery attempt for LND-2291 was unsuccessful at the border checkpoint. Would you like to reschedule?",
          timestamp: time(-1, 17, 5),
          buttons: ["Reschedule", "Contact driver"],
        },
      ],
      cost_breakdown: [
        { id: "c1", item: "Border parking", amount: 750, category: "warehousing" },
        { id: "c2", item: "Transit paperwork", amount: 1200, category: "broker" },
        { id: "c3", item: "Cross-border trailer", amount: 4200, category: "trucking" },
        { id: "c4", item: "Forwarding fee", amount: 1600, category: "service_fee" },
      ],
      partner_coordination_log: [
        {
          id: "p1",
          party: "Batha Clearance Partners",
          role: "customs_broker",
          text: "Certificate of origin required before re-attempt.",
          timestamp: time(-1, 18, 2),
        },
      ],
      created_at: iso(-3),
    },
    {
      id: "SEA-7731",
      customer_name: "مؤسسة النخيل للأغذية",
      customer_phone: "+971 56 220 9014",
      customer_language: "ar",
      shipper: "Al Nakheel Foodstuff Est.",
      consignee: "Karachi Wholesale Foods",
      cargo_type: "Dates & dry goods",
      weight: 24000,
      origin: "Port Rashid, Dubai",
      destination: "Karachi, Pakistan",
      mode: "sea",
      booking_date: iso(-9),
      status: "out_for_delivery",
      cod_amount: 9400,
      missing_docs: [],
      ai_summary: {
        en: "A 24-tonne sea consignment of dates and dry goods arrived in Karachi and is out for final delivery. Documents are complete and AED 9,400 COD is to be collected on handover.",
        ar: "شحنة بحرية بوزن ٢٤ طن من التمور والمواد الجافة وصلت إلى كراتشي وهي خارجة للتسليم النهائي. المستندات مكتملة، وسيتم تحصيل ٩٬٤٠٠ درهم عند التسليم.",
      },
      whatsapp_log: [
        {
          id: "w1",
          direction: "out",
          text: "شحنتكم SEA-7731 خارجة للتسليم اليوم. يرجى تجهيز مبلغ ٩٬٤٠٠ درهم عند الاستلام.",
          timestamp: time(0, 8, 30),
          buttons: ["تأكيد", "التواصل مع السائق"],
        },
      ],
      cost_breakdown: [
        { id: "c1", item: "Port storage", amount: 1900, category: "warehousing" },
        { id: "c2", item: "Import clearance", amount: 1500, category: "broker" },
        { id: "c3", item: "Local delivery", amount: 1100, category: "trucking" },
        { id: "c4", item: "Forwarding fee", amount: 2100, category: "service_fee" },
      ],
      partner_coordination_log: [
        {
          id: "p1",
          party: "Indus Last-Mile Couriers",
          role: "last_mile",
          text: "Driver assigned, ETA 3 hours.",
          timestamp: time(0, 8, 15),
        },
      ],
      created_at: iso(-9),
    },
    {
      id: "AIR-6650",
      customer_name: "Falcon Medical Supplies",
      customer_phone: "+971 50 663 1120",
      customer_language: "en",
      shipper: "Falcon Medical Supplies",
      consignee: "Nairobi Health Distributors",
      cargo_type: "Medical consumables",
      weight: 780,
      origin: "Sharjah Airport",
      destination: "Nairobi, Kenya",
      mode: "air",
      booking_date: iso(-1),
      status: "booked",
      cod_amount: 0,
      missing_docs: ["certificate_of_origin"],
      ai_summary: {
        en: "A 780 kg air booking of medical consumables from Sharjah to Nairobi is confirmed and awaiting departure. The certificate of origin has not yet been received.",
        ar: "حجز جوي بوزن ٧٨٠ كجم من المستلزمات الطبية من الشارقة إلى نيروبي تم تأكيده وينتظر الإقلاع. لم يتم استلام شهادة المنشأ بعد.",
      },
      whatsapp_log: [
        {
          id: "w1",
          direction: "out",
          text: "Your booking AIR-6650 is confirmed for departure from Sharjah. We'll notify you when it departs.",
          timestamp: time(-1, 12, 5),
          buttons: ["Confirm"],
        },
      ],
      cost_breakdown: [
        { id: "c1", item: "Cold storage staging", amount: 900, category: "warehousing" },
        { id: "c2", item: "Export permit filing", amount: 700, category: "broker" },
        { id: "c3", item: "Pickup from warehouse", amount: 420, category: "trucking" },
        { id: "c4", item: "Forwarding fee", amount: 1250, category: "service_fee" },
      ],
      partner_coordination_log: [
        {
          id: "p1",
          party: "Sharjah Origin Desk",
          role: "origin_agent",
          text: "Cargo received, awaiting COO to build AWB.",
          timestamp: time(-1, 13, 0),
        },
      ],
      created_at: iso(-1),
    },
    {
      id: "LND-4408",
      customer_name: "Dune Retail Group",
      customer_phone: "+971 54 880 2211",
      customer_language: "en",
      shipper: "Dune Retail Group",
      consignee: "Muscat Grand Stores",
      cargo_type: "Home appliances",
      weight: 5400,
      origin: "Al Quoz, Dubai",
      destination: "Muscat, Oman",
      mode: "land",
      booking_date: iso(-2),
      status: "in_transit",
      cod_amount: 22600,
      missing_docs: [],
      ai_summary: {
        en: "A 5.4-tonne road shipment of home appliances is moving from Al Quoz to Muscat with all documents in place. AED 22,600 will be collected on delivery.",
        ar: "شحنة برية بوزن ٥.٤ طن من الأجهزة المنزلية في طريقها من القوز إلى مسقط وجميع المستندات مكتملة. سيتم تحصيل ٢٢٬٦٠٠ درهم عند التسليم.",
      },
      whatsapp_log: [
        {
          id: "w1",
          direction: "out",
          text: "Shipment LND-4408 is In Transit to Muscat. Please keep AED 22,600 ready for collection on delivery.",
          timestamp: time(-2, 10, 10),
          buttons: ["Confirm", "Reschedule"],
        },
      ],
      cost_breakdown: [
        { id: "c1", item: "Cross-dock handling", amount: 620, category: "warehousing" },
        { id: "c2", item: "Hatta border filing", amount: 850, category: "broker" },
        { id: "c3", item: "Curtain-side trailer", amount: 2400, category: "trucking" },
        { id: "c4", item: "Forwarding fee", amount: 1500, category: "service_fee" },
      ],
      partner_coordination_log: [
        {
          id: "p1",
          party: "Hatta Border Brokers",
          role: "customs_broker",
          text: "Manifest cleared at Hatta crossing.",
          timestamp: time(-1, 6, 45),
        },
      ],
      created_at: iso(-2),
    },
    {
      id: "SEA-5120",
      customer_name: "شركة المرجان للمعدات",
      customer_phone: "+971 58 331 7742",
      customer_language: "ar",
      shipper: "Al Murjan Equipment Co.",
      consignee: "Rotterdam Machine Works",
      cargo_type: "Industrial pumps",
      weight: 31000,
      origin: "Khalifa Port, Abu Dhabi",
      destination: "Rotterdam, Netherlands",
      mode: "sea",
      booking_date: iso(-14),
      status: "in_transit",
      cod_amount: 0,
      missing_docs: ["packing_list"],
      ai_summary: {
        en: "A 31-tonne sea shipment of industrial pumps is sailing from Khalifa Port to Rotterdam. The packing list is still missing from the file.",
        ar: "شحنة بحرية بوزن ٣١ طن من المضخات الصناعية مبحرة من ميناء خليفة إلى روتردام. قائمة التعبئة ما زالت ناقصة في الملف.",
      },
      whatsapp_log: [
        {
          id: "w1",
          direction: "out",
          text: "شحنتكم SEA-5120 قيد النقل إلى روتردام. المدة التقديرية ١٨ يومًا.",
          timestamp: time(-14, 9, 0),
          buttons: ["تأكيد"],
        },
      ],
      cost_breakdown: [
        { id: "c1", item: "Heavy-lift staging", amount: 3200, category: "warehousing" },
        { id: "c2", item: "Export clearance", amount: 1100, category: "broker" },
        { id: "c3", item: "Low-bed haulage", amount: 3800, category: "trucking" },
        { id: "c4", item: "Forwarding fee", amount: 2600, category: "service_fee" },
      ],
      partner_coordination_log: [
        {
          id: "p1",
          party: "Khalifa Origin Agent",
          role: "origin_agent",
          text: "Lashing certificate issued, vessel sailed on schedule.",
          timestamp: time(-14, 10, 25),
        },
      ],
      created_at: iso(-14),
    },
    {
      id: "AIR-3377",
      customer_name: "Sahara Fashion House",
      customer_phone: "+971 50 774 8890",
      customer_language: "en",
      shipper: "Sahara Fashion House",
      consignee: "Milano Retail Group",
      cargo_type: "Apparel",
      weight: 1150,
      origin: "DXB Cargo Terminal, Dubai",
      destination: "Milan, Italy",
      mode: "air",
      booking_date: iso(-4),
      status: "delivered",
      cod_amount: 0,
      missing_docs: [],
      ai_summary: {
        en: "A 1,150 kg air shipment of apparel from Dubai to Milan has been delivered with full documentation and no outstanding COD.",
        ar: "شحنة جوية بوزن ١٬١٥٠ كجم من الملابس من دبي إلى ميلانو تم تسليمها بمستندات كاملة وبدون مبالغ مستحقة.",
      },
      whatsapp_log: [
        {
          id: "w1",
          direction: "out",
          text: "Shipment AIR-3377 has been delivered in Milan. Thank you for shipping with us.",
          timestamp: time(-2, 14, 40),
          buttons: ["Confirm"],
        },
      ],
      cost_breakdown: [
        { id: "c1", item: "Airline terminal fee", amount: 1400, category: "warehousing" },
        { id: "c2", item: "Import clearance Milan", amount: 1650, category: "broker" },
        { id: "c3", item: "Final mile van", amount: 700, category: "trucking" },
        { id: "c4", item: "Forwarding fee", amount: 1750, category: "service_fee" },
      ],
      partner_coordination_log: [
        {
          id: "p1",
          party: "Lombardia Last-Mile",
          role: "last_mile",
          text: "Delivered and signed at 14:32 CET.",
          timestamp: time(-2, 14, 35),
        },
      ],
      created_at: iso(-4),
    },
    {
      id: "LND-9954",
      customer_name: "مجموعة الظفرة للمقاولات",
      customer_phone: "+971 55 118 6602",
      customer_language: "ar",
      shipper: "Al Dhafra Contracting Group",
      consignee: "Doha Site Works",
      cargo_type: "Steel fittings",
      weight: 7200,
      origin: "Al Ain, UAE",
      destination: "Doha, Qatar",
      mode: "land",
      booking_date: iso(0),
      status: "booked",
      cod_amount: 6300,
      missing_docs: ["commercial_invoice", "bill_of_lading"],
      ai_summary: {
        en: "A 7.2-tonne road booking of steel fittings from Al Ain to Doha is confirmed for pickup. Two key documents are outstanding and AED 6,300 COD applies.",
        ar: "حجز بري بوزن ٧.٢ طن من التجهيزات الفولاذية من العين إلى الدوحة تم تأكيده للاستلام. هناك مستندان أساسيان ناقصان ومبلغ ٦٬٣٠٠ درهم مستحق عند الاستلام.",
      },
      whatsapp_log: [
        {
          id: "w1",
          direction: "out",
          text: "تم تأكيد حجز شحنتكم LND-9954 من العين إلى الدوحة. سنبلغكم عند انطلاق الشاحنة.",
          timestamp: time(0, 7, 55),
          buttons: ["تأكيد", "إعادة الجدولة"],
        },
      ],
      cost_breakdown: [
        { id: "c1", item: "Yard staging", amount: 480, category: "warehousing" },
        { id: "c2", item: "Export filing", amount: 620, category: "broker" },
        { id: "c3", item: "Flatbed booking", amount: 2900, category: "trucking" },
        { id: "c4", item: "Forwarding fee", amount: 1200, category: "service_fee" },
      ],
      partner_coordination_log: [
        {
          id: "p1",
          party: "Al Ain Origin Desk",
          role: "origin_agent",
          text: "Waiting on commercial invoice before loading.",
          timestamp: time(0, 8, 10),
        },
      ],
      created_at: iso(0),
    },
  ];
}

export function makeSeedCash(): CashEntry[] {
  return [
    {
      id: "INV-1041",
      shipment_id: "SEA-8842",
      type: "receivable",
      party_name: "Al Barsha Trading LLC",
      amount: 22400,
      due_date: iso(-9),
      status: "pending",
    },
    {
      id: "INV-1042",
      shipment_id: "LND-2291",
      type: "receivable",
      party_name: "Oasis Construction Supplies",
      amount: 16900,
      due_date: iso(-2),
      status: "pending",
    },
    {
      id: "INV-1043",
      shipment_id: "SEA-7731",
      type: "receivable",
      party_name: "Al Nakheel Foodstuff Est.",
      amount: 13800,
      due_date: iso(12),
      status: "pending",
    },
    {
      id: "INV-1044",
      shipment_id: "LND-4408",
      type: "receivable",
      party_name: "Dune Retail Group",
      amount: 27500,
      due_date: iso(26),
      status: "pending",
    },
    {
      id: "INV-1045",
      shipment_id: "SEA-5120",
      type: "receivable",
      party_name: "Al Murjan Equipment Co.",
      amount: 41200,
      due_date: iso(48),
      status: "pending",
    },
    {
      id: "INV-1039",
      shipment_id: "AIR-3377",
      type: "receivable",
      party_name: "Sahara Fashion House",
      amount: 9800,
      due_date: iso(-20),
      status: "paid",
    },
    {
      id: "PAY-2201",
      shipment_id: "SEA-8842",
      type: "payable",
      party_name: "Gulf Line Shipping (carrier)",
      amount: 14600,
      due_date: iso(5),
      status: "pending",
    },
    {
      id: "PAY-2202",
      shipment_id: "AIR-6650",
      type: "payable",
      party_name: "Sharjah Air Handling",
      amount: 8300,
      due_date: iso(8),
      status: "pending",
    },
    {
      id: "PAY-2203",
      shipment_id: "LND-4408",
      type: "payable",
      party_name: "Hatta Border Brokers",
      amount: 6100,
      due_date: iso(11),
      status: "pending",
    },
    {
      id: "PAY-2204",
      shipment_id: "SEA-5120",
      type: "payable",
      party_name: "Khalifa Port Warehousing",
      amount: 19400,
      due_date: iso(14),
      status: "pending",
    },
    {
      id: "PAY-2205",
      shipment_id: "SEA-7731",
      type: "payable",
      party_name: "Indus Last-Mile Couriers",
      amount: 7200,
      due_date: iso(21),
      status: "pending",
    },
    {
      id: "PAY-2206",
      shipment_id: null,
      type: "payable",
      party_name: "Fleet fuel & maintenance",
      amount: 11500,
      due_date: iso(34),
      status: "pending",
    },
    {
      id: "PAY-2207",
      shipment_id: "LND-9954",
      type: "payable",
      party_name: "Al Ain Flatbed Transport",
      amount: 9700,
      due_date: iso(52),
      status: "pending",
    },
  ];
}

export const SAMPLE_EMAIL = `Subject: Booking confirmation – 2 x 40HC ex Jebel Ali

Dear Ops team,

Please arrange sea freight for Horizon Marine Supplies (contact Mr. Rashid, +971 50 442 9087, prefers English).
Shipper: Horizon Marine Supplies FZE, Jebel Ali Free Zone
Consignee: Mombasa Port Services Ltd, Kenya
Cargo: marine ropes and deck fittings, 2 x 40HC, gross weight approx 21,500 kg
Origin: Jebel Ali, Dubai   Destination: Mombasa, Kenya
Requested sailing: this Thursday.
COD to be collected on delivery: AED 15,750.

Commercial invoice and packing list attached. Certificate of origin will follow.

Best regards,
Rashid A.`;
